<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DriversRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriversRepository extends EntityRepository
{
    public function findAllDriversSubmitted($drivers)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT d FROM AppBundle:Drivers d
                 WHERE d.id IN (:ids)'
            )->setParameters(array('ids' => $drivers));

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
