<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InviteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteUserRepository extends EntityRepository
{
    public function findAllInvitedLeagues($email,$season)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT i, l, u FROM AppBundle:InviteUser i
                 JOIN i.league l
                 LEFT JOIN l.fos_user u
                 WHERE i.email = :email
                 AND i.season = :season
                 AND i.accepted = 0
                 AND i.declined = 0'
            )->setParameters(array('email' => $email, 'season' => $season));

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
