<?php

namespace AppBundle\Repository;

/**
 * LeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function findAllMyActiveLeagues($uid)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ul, l FROM AppBundle:UserLeagues ul
                 JOIN ul.league l
                 WHERE l.disabled = 0
                 AND ul.user_id = :uid'
            )->setParameter('uid', $uid);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }*/
}
