<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaceResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceResultsRepository extends EntityRepository
{
    public function getResultsByRaceIDs($ids) {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT rr FROM AppBundle:RaceResults rr
                 WHERE rr.id IN (:ids)'
            )->setParameters(array('ids'=>$ids));

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
