<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaceSubmissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceSubmissionsRepository extends EntityRepository
{
    public function getUsersFromRaceSubmissions($race,$league)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT rs FROM AppBundle:RaceSubmissions rs
                 WHERE rs.race = :race
                 AND rs.league = :league'
            )->setParameters(['race'=>$race, 'league'=>$league]);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getFosUserSubmissions($ids) {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u
                 WHERE u.id IN (:ids)'
            )->setParameters(array('ids'=>$ids));

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getCompletedRaceSubmissions($ids,$league) {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT rs FROM AppBundle:RaceSubmissions rs
                 WHERE rs.race IN (:ids)
                 AND rs.league = :league'
            )->setParameters(array('ids'=>$ids, 'league'=>$league));
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
