<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaceScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceScheduleRepository extends EntityRepository
{


}
