# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.form.registration:
      class: AppBundle\Form\Type\RegistrationFormType
      tags:
          - { name: form.type, alias: fos_user_registration }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


  app.league_manager:
      class: AppBundle\Service\LeagueManager
      arguments: ['@session','@doctrine.orm.entity_manager']


  app.drivers_manager:
      class: AppBundle\Service\DriversManager
      arguments: ['@session','@doctrine.orm.entity_manager']

  app.email_manager:
      class: AppBundle\Service\EmailManager
      arguments: ['@mailer', '@twig', '@doctrine.orm.entity_manager']